name: plakman-v0.0.16
services:
  plakman:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      SSH_AUTH_SOCK: /var/lib/plakman/ssh-agent.sock
    image: "ghcr.io/plakarkorp/plakman:v0.0.16"
    restart: always
    labels:
      logging.service: plakman
    configs:
      - source: plakman_config
        target: /plakman.yaml 
    volumes:
      - /data/plakman_runtime:/var/lib/plakman
      - /data/logs:/logs
    entrypoint: /usr/local/bin/plakman -foreground -config /plakman.yaml
    networks: [edge]
    secrets:
      - pg_password
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 12
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  vector:
    image: timberio/vector:latest-alpine
    restart: unless-stopped
    configs:
      - source: vector_config
        target: /etc/vector/vector.toml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/logs:/logs
    command: -c /etc/vector/vector.toml

networks:
  edge:
    name: edge
    driver: bridge

secrets:
  pg_password:
    file: /data/secrets/db_password

configs:
  vector_config:
    content: |
      [sources.docker]
      type = "docker_logs"
      exclude_containers = ["vector"]

      [transforms.add_service]
      type = "remap"
      inputs = ["docker"]
      source = '''
      .service = .label."logging.service"
      del(.label)
      '''
      [sinks.file]
      type = "file"
      inputs = ["add_service"]
      path = "/logs/plakman-logs-%Y-%m-%d.log.gz"
      compression = "gzip"
      encoding.codec = "json"


  plakman_config:
    content: |
      services:
        http:
          listen:
            address: :8080
        database:
          url: postgres://plakman:plakman@postgres:5432/plakman-db
        plakman:
          parentUrl: https://api.plakar.io
          stateDirectory: /var/lib/plakman/
        scheduler:
          plakmanUrl: http://plakman:8080
        executor:
          pkgDir: /var/lib/plakman/pkgs/
          plakmanUrl: http://plakman:8080
          plakletBin: /usr/local/bin/plaklet
          cachedBin: /usr/local/bin/cached
        journal:
          dbStorage: true
          logPath: /var/lib/plakman/journal.log
      api:
        v1:
          mode:
            plakman: true
            plakario: false
          cors: true
          auth:
            emailRedirect: "http://localhost:8080/api/v1/auth/login/email/callback"
